OPENAI_API_KEY = "sk-proj-4QGgO6yp8ntZNG0p6nPuT3BlbkFJ88XMp74D962VO39Gf3us"
AYUDAS_QUESTION_ASSISTANT_ID = "asst_07AIGb5BcNbAl9C3q3uIr5KC"
ANTHROPIC_API_KEY = "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"
PROBLEM_STATEMENT_AI = "asst_lUCHGiQO31jtyl0GElPSCeNH"